### ISSUE TITLE
[Offer] Publish on Steam

### ISSUE THREAD

**Issue by SSyl** [alexemanuelol/RustDaVinci#13]
Hi,

I know you haven't been actively working on this much, but I'd be happy to front you the $100 to publish it on Steam so it becomes EAC Friendly/Compatible with Rust.

I'd leave the project in your hands entirely and I wouldn't have any stipulations or requirements from you. Basically, as long as you keep it working with Rust.

Also, any future profits that you might make on it would be entirely your own (if you decide to add a "Pro" version or even just a $5 "supporter" version just for donations).

Essentially, I'd just give you $100 (via PayPal or whatever you prefer), you make sure it's working with the current version of Rust/EAC and publish it on Steam, and I'm okay with anything you do in the future.

Let me know your thoughts and if you'd like to get in touch.

**Comment by alexemanuelol** [comment]
Hello SSyl, sorry for the late response!

Thank you for the very generous offer! I have actually thought about publishing it on steam but before I would do that I would like to rework a lot of the code. There are a lot of smelly code in RustDaVinci unfortunately 🤢 And currently I'm quite occupied with other/future projects so I'm not sure when I'll get time to work on this again.

Btw, thank you for supporting the Rust++ project 😃

**Comment by SSyl** [comment]
No worries about the late response! If you do decide to publish it in the future, let me know. I'm more than happy to throw some money to projects I like!
